### ISSUE TITLE
Crash when interacting with Chocobo egg in any way with Reskillable installed.

### ISSUE THREAD

**Issue by coldReactive** [Slayer5934/ChocoCraft3SLY#27]
Crash Report: https://pastebin.com/qUxJ5VVb

When using a chocopedia on a chocobo egg, the client crashes. This was done in creative mode.

**Comment by SlayerTheChikken** [comment]
@coldReactive Looks like the issue is coming from Reskillable, I'll take a deeper look though.

**Comment by SlayerTheChikken** [comment]
Some things to note.
1. It happens even without any item in your hand. 
2. It only crashes if you RE- PLACE the egg down on the ground OR if the egg has just been hatched. (If the egg is already placed when joining the game it doesn't happen.)
3. It happens when trying to mine it as-well as right click it.

**Comment by SlayerTheChikken** [comment]
Should be solved now ab005fb23b156dcf2fa4b47fde6aef07c7a470d2
